version: "3"

services:
    nginx:
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./:/var/www/
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - php_fpm
        container_name: project_nginx
    php_fpm:
        restart: unless-stopped
        build:
            context: .
            dockerfile: _docker/php-fpm/DockerFile
        volumes:
            - ./:/var/www
        depends_on:
            - mysql
        container_name: project_php
    mysql:
        image: mysql:8.0
        restart: unless-stopped
        #ports:
        #    - 3306:3306
        volumes:
            - ./_docker/mysql/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: heater
            MYSQL_USER: webdev
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: 12345
        container_name: project_db
    pma:
        image: phpmyadmin:latest
        restart: unless-stopped
        ports:
            - 81:80
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            MYSQL_USER: webdev
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: 12345
        container_name: project_pma
