FROM php:7.4-fpm

# Arguments defined in docker-compose.yml
	ARG user
	ARG uid	
# Install system dependencies
	RUN apt-get update \
	  && apt-get install -y \
		 apt-utils \
		 git \
		 vim \
		 man \
		 curl \
		 pkg-config \
		 icu-devtools \
		 libicu-dev \
		 libcurl4 \
		 libfreetype6-dev \
		 libjpeg62-turbo-dev \
		 libpng-dev \
		 libjpeg-dev \
		 libbz2-dev \
		 libssl-dev \
		 libgmp-dev \
		 libtidy-dev \
		 libxml2-dev \
		 libxslt1-dev \
		 libzip-dev \
		 libonig-dev \
		 libcurl4-openssl-dev \
		 autoconf \
	  &&  ln -s /usr/include/x86_64-linux-gnu/gmp.h /usr/include/gmp.h

	RUN docker-php-ext-install mysqli \
		&& docker-php-ext-install pdo_mysql \
		&& docker-php-ext-install intl \
		&& docker-php-ext-install zip \
		&& docker-php-ext-install bz2 \
		&& docker-php-ext-install calendar \
		&& docker-php-ext-install bcmath \
		&& docker-php-ext-install exif \
		&& docker-php-ext-install gettext \
		&& docker-php-ext-install gmp \
		&& docker-php-ext-install mbstring \
		&& docker-php-ext-install pcntl \
		&& docker-php-ext-install shmop \
		&& docker-php-ext-install sockets \
		&& docker-php-ext-install sysvmsg \
		&& docker-php-ext-install sysvsem \
		&& docker-php-ext-install sysvshm \
		&& docker-php-ext-install tidy \
		&& docker-php-ext-install xsl \
		&& docker-php-ext-install gd \
		&& docker-php-ext-install curl \
		&& docker-php-source delete
		
	RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
	  && docker-php-ext-install -j$(nproc) gd \
	  && docker-php-source delete
	
	RUN apt update && apt install -y git
    ADD ./_docker/php_fpm/php.ini /usr/local/etc/php/conf.d/
# Install composer
#	ENV COMPOSER_ALLOW_SUPERUSER=1
#	RUN curl -sS https://getcomposer.org/installer | php -- \
#		--filename=composer \
#		--install-dir=/usr/local/bin
# Clear cache
#	RUN apt-get clean && rm -rf /var/lib/apt/lists/*
# Get latest Composer
	COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
# Create system user to run Composer and Artisan Commands
	RUN useradd -G www-data,root -u $uid -d /home/$user $user
	RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user
# Set working directory
WORKDIR /var/www
USER $user
